### ISSUE TITLE
Can not download Facebook Video

### ISSUE THREAD

**Issue by SArsalanK** [capturemathan/VideoDownloader#6]
java.net.UnknownHostException: Unable to resolve host "www.getfvid.com": No address associated with hostname
2019-07-11 15:49:51.625 19269-20139/com.allvideodownloader.socialmedia.videodownloader W/System.err:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:141)
2019-07-11 15:49:51.625 19269-20139/com.allvideodownloader.socialmedia.videodownloader W/System.err:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
2019-07-11 15:49:51.625 19269-20139/com.allvideodownloader.socialmedia.videodownloader W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:787)
2019-07-11 15:49:51.625 19269-20139/com.allvideodownloader.socialmedia.videodownloader W/System.err:     at com.android.okhttp.Dns$1.lookup(Dns.java:39)
2019-07-11 15:49:51.625 19269-20139/com.allvideodownloader.socialmedia.videodownloader W/System.err:     at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
2019-07-11 15:49:51.626 19269-20139/com.allvideodownloader.socialmedia.videodownloader W/System.err:     at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
2019-07-11 15:49:51.626 19269-20139/com.allvideodownloader.socialmedia.videodownloader W/System.err:     at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
2019-07-11 15:49:51.626 19269-20139/com.allvideodownloader.socialmedia.videodownloader W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
2019-07-11 15:49:51.626 19269-20139/com.allvideodownloader.socialmedia.videodownloader W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
2019-07-11 15:49:51.626 19269-20139/com.allvideodownloader.socialmedia.videodownloader W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
2019-07-11 15:49:51.626 19269-20139/com.allvideodownloader.socialmedia.videodownloader W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
2019-07-11 15:49:51.626 19269-20139/com.allvideodownloader.socialmedia.videodownloader W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
2019-07-11 15:49:51.626 19269-20139/com.allvideodownloader.socialmedia.videodownloader W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
2019-07-11 15:49:51.627 19269-20139/com.allvideodownloader.socialmedia.videodownloader W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
2019-07-11 15:49:51.628 19269-20139/com.allvideodownloader.socialmedia.videodownloader W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
2019-07-11 15:49:51.628 19269-20139/com.allvideodownloader.socialmedia.videodownloader W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(Unknown Source:0)
2019-07-11 15:49:51.628 19269-20139/com.allvideodownloader.socialmedia.videodownloader W/System.err:     at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:571)
2019-07-11 15:49:51.628 19269-20139/com.allvideodownloader.socialmedia.videodownloader W/System.err:     at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:548)
2019-07-11 15:49:51.628 19269-20139/com.allvideodownloader.socialmedia.videodownloader W/System.err:     at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:235)
2019-07-11 15:49:51.629 19269-20139/com.allvideodownloader.socialmedia.videodownloader W/System.err:     at org.jsoup.helper.HttpConnection.post(HttpConnection.java:230)
2019-07-11 15:49:51.629 19269-20139/com.allvideodownloader.socialmedia.videodownloader W/System.err:     at com.allvideodownloader.socialmedia.videodownloader.DownloadActivity$Facebook.doInBackground(DownloadActivity.java:227)
2019-07-11 15:49:51.629 19269-20139/com.allvideodownloader.socialmedia.videodownloader W/System.err:     at com.allvideodownloader.socialmedia.videodownloader.DownloadActivity$Facebook.doInBackground(DownloadActivity.java:210)
2019-07-11 15:49:51.629 19269-20139/com.allvideodownloader.socialmedia.videodownloader W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)

**Comment by capturemathan** [comment]
You can't download videos of PRIVATE Page or PRIVATE Profile
